- name: Configure new machine
  hosts: server
  become: True
  tasks:
    - include_tasks: tasks/01_install_requirements.yml
    - include_tasks: tasks/02_setup_global_pyenv.yml
      vars:
        python_version: "3.10.0"
    # - include_tasks: tasks/10_create_groups.yml
    - include_tasks: tasks/11_create_admin_user.yml
      vars:
        username: "{{ admin_username }}"
        uid: 1001
        password: "{{ admin_password | password_hash('sha512') }}"
        ssh_pubkey: "{{ admin_ssh_pubkey }}"
    - include_tasks: tasks/20_create_normal_user.yml
      vars:
        username: "{{ normal_username }}"
        uid: 2001
        password: "{{ normal_password | password_hash('sha512') }}"
        ssh_pubkey: "{{ normal_ssh_pubkey }}"

    - include_tasks: tasks/30_ssh_settings.yml
    - include_tasks: tasks/40_ufw_settings.yml
    - include_tasks: tasks/99_reboot.yml
