# See : https://github.com/pyenv/pyenv/wiki#suggested-build-environment
- name: "Install requirements"
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
      - git
      - docker
      - docker-compose
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
      - acl
