- name: "Install requirements"
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - dbus-user-session
      - gnupg
      - gnupg-agent
      - lsb-release
      - slirp4netns
      - software-properties-common
      - uidmap
  become: yes

# - name: install slirp4netns for Ubuntu <= 19
#   copy: src=./files/{{item}} dest=/usr/local/bin/{{item}} owner=root group=root mode=0755
#   with_items:
#     - "slirp4netns"
#   when:
#     - ansible_facts['distribution'] == "Ubuntu"
#     - ansible_facts['distribution_major_version'] <= "19"

- name: "Add Docker's official GPG key for docker"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: yes

- name: "Set up the stable repository for docker"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  become: yes

- name: "Install docker engine"
  apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  become: yes

- name: "Install docker-compose"
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: +x
  become: yes

- name: "Disable rootful deamons"
  # shell: systemctl disable --now docker.service
  systemd:
    name: docker.service
    state: stopped
    enabled: no

- name: "Disable rootful deamons"
  # shell: systemctl disable --now docker.socket
  systemd:
    name: docker.socket
    state: stopped
    enabled: no

- name: "Add nvidia-docker repository key"
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present
- name: "Add nvidia-docker repository source"
  get_url:
    url: https://nvidia.github.io/nvidia-docker/{{ ansible_distribution | lower }}{{ ansible_distribution_version }}/nvidia-docker.list
    dest: /etc/apt/sources.list.d/nvidia-docker.list
    owner: root
    group: root
    mode: 0644

# - name: "Set up the stable repository and GPG key for nvidia-docker"
#   shell: |
#     distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
#     && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
#     && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

- name: "Install nvidia-docker2"
  apt:
    update_cache: yes
    name:
      - nvidia-docker2

- name: "Hold docker version"
  dpkg_selections:
    selection: hold
    name: docker-ce

- name: "Hold nvidia-docker version"
  dpkg_selections:
    selection: hold
    name: nvidia-docker2

- name: "Rewrite no-cgroups"
  replace:
    path: /etc/nvidia-container-runtime/config.toml
    regexp: "^#? *no-cgroups *= *false$"
    replace: "no-cgroups = true"

# - name: "Set docker rootless host"
#   copy: src=etc/{{item}} dest=/etc/profile.d/{{item}} owner=root group=root mode=0755
#   with_items:
#     - "set-docker-rootless-host.sh"

- name: "Set docker rootless host to .bashrc"
  blockinfile:
    insertafter: EOF
    marker: ""
    path: /etc/profile
    block: |
      # dockerd-rootless-setuptool.sh install
      export DOCKER_HOST="unix://${XDG_RUNTIME_DIR}/docker.sock"
