- name: "Create common user: {{ username }}"
  user:
    name: "{{ username }}"
    # For simplicity.
    # uid: "{{ uid }}"
    # If you create additional user groups with `10_create_groups.yml`
    # DON'T forget to add line like following.
    # group: common
    create_home: yes
    home: "/home/{{ username }}"
    password: "{{ password }}"
    update_password: on_create
    shell: /bin/bash

### SSH config
- include_tasks: _ssh_config.yml
  vars:
    home: "/home/{{ username }}"
